FROM python:3.10

ENV SHELL=/bin/bash

WORKDIR /src

COPY ./requirements.txt ./requirements.txt

RUN apt-get update \
    && apt-get install -y gcc python3-dev \
    && pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./src .
 
COPY  ./src/frontend/ /usr/local/lib/python3.10/site-packages/chainlit/frontend/dist/


CMD ["chainlit", "run","-w", "server.py", "--port", "7860"]

